<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-GestPR-030de683-53c3-449b-9ba2-f33df6663398</UserSecretsId>
	  <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
	  <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
	  <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
	  <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
	  <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
	  <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
	  <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.26" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.16.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.DirectoryServices" Version="10.0.9" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.9" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
    <Folder Include="Application\" />
    <Folder Include="Infrastructure\" />
    <Folder Include="Service\File\" />
    <Folder Include="WebApi\" />
  </ItemGroup>

	
</Project>
